# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

#-- VPC IP Address --#
ZOOKEEPER_IP = "172.30.0.10"
NIMBUS_IP = "172.30.0.11"
SUPERVISOR_IPs = ["172.30.0.12", "172.30.0.13", "172.30.0.14"]
DRPC_IP = "172.30.0.15"

STORM_VERSION = "0.10.0-SNAPSHOT"

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "zookeeper" do |zookeeper|
    zookeeper.vm.box = 'precise64'
    zookeeper.vm.network "private_network", ip: ZOOKEEPER_IP
    zookeeper.vm.hostname = "zookeeper"
    zookeeper.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["../../site-cookbooks", "../../cookbooks"]
      chef.add_recipe "base"
    end
  end

  config.vm.define "nimbus" do |nimbus|
    nimbus.vm.box = 'precise64'
    nimbus.vm.network "private_network", ip: NIMBUS_IP
    nimbus.vm.hostname = "nimbus"
    nimbus.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["../../site-cookbooks", "../../cookbooks"]
      chef.add_recipe "storm-cluster::nimbus"
      chef.json = {
        "storm" => {
          "storm_yaml" => {
            "nimbus.host" => NIMBUS_IP,
            "storm.zookeeper.servers" => [ZOOKEEPER_IP],
            "drpc.servers" => [DRPC_IP]
          },
          "version" => STORM_VERSION
        }
      }
    end
  end

  (1..3).each do |i|
    config.vm.define "supervisor#{i}" do |supervisor|
      supervisor.vm.box = 'precise64'
      supervisor.vm.network "private_network", ip: SUPERVISOR_IPs[i-1]
      supervisor.vm.hostname = "supervisor#{i}"
      supervisor.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ["../../site-cookbooks", "../../cookbooks"]
        chef.add_recipe "storm-cluster::supervisor"
        chef.json = {
          "storm" => {
            "storm_yaml" => {
              "nimbus.host" => NIMBUS_IP,
              "storm.zookeeper.servers" => [ZOOKEEPER_IP],
              "drpc.servers" => [DRPC_IP]
            },
            "version" => STORM_VERSION
          }
        }
      end
    end
  end

  config.vm.define "drpc" do |drpc|
    drpc.vm.box = 'precise64'
    drpc.vm.network "private_network", ip: DRPC_IP
    drpc.vm.hostname = "drpc"
    drpc.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["../../site-cookbooks", "../../cookbooks"]
      chef.add_recipe "storm-cluster::drpc"
      chef.json = {
        "storm" => {
          "storm_yaml" => {
            "nimbus.host" => NIMBUS_IP,
              "storm.zookeeper.servers" => [ZOOKEEPER_IP],
            "drpc.servers" => [DRPC_IP]
          },
          "version" => STORM_VERSION
        }
      }
    end
  end
end
